export const config = {
  filePath: '../static/2020/055_Adjuntas_LEGISLATIVA_17-1.jpg',
  N_COLUMNS: 6,
  CELL_WIDTH: 385,
  STARTING_X: 195,
  PERCENTAGE_DELTA: 0.01,
  rows: [
    {
      IMAGE_NAME_PREFIX: '1-partido',
      MAIN_TOP: 110,
      MAIN_HEIGHT: 255,
      hasLogos: true,
      N_LOGO: 5,
      LOGO_TOP: 115,
      LOGO_HEIGHT: 110,
      LOGO_LEFT_DELTA: 130,
      LOGO_RIGHT_DELTA: 265,
    },
    {
      IMAGE_NAME_PREFIX: '2-representates-distrito-titular',
      MAIN_TOP: 370,
      MAIN_HEIGHT: 60,
      hasLogos: false,
    },
    {
      IMAGE_NAME_PREFIX: '3-representates-distrito',
      MAIN_TOP: 430,
      MAIN_HEIGHT: 60,
      hasLogos: true,
      N_LOGO: 3,
      LOGO_TOP: 430,
      LOGO_HEIGHT: 60,
      LOGO_LEFT_DELTA: 120,
      LOGO_RIGHT_DELTA: 330,
    },
    {
      IMAGE_NAME_PREFIX: '4-senadores-titular',
      MAIN_TOP: 495,
      MAIN_HEIGHT: 60,
      hasLogos: false,
    },
    {
      IMAGE_NAME_PREFIX: '5-senadores-1',
      MAIN_TOP: 555,
      MAIN_HEIGHT: 60,
      hasLogos: true,
      N_LOGO: 5,
      LOGO_TOP: 555,
      LOGO_HEIGHT: 60,
      LOGO_LEFT_DELTA: 120,
      LOGO_RIGHT_DELTA: 330,
    },
    {
      IMAGE_NAME_PREFIX: '6-senadores-2',
      MAIN_TOP: 620,
      MAIN_HEIGHT: 60,
      hasLogos: true,
      N_LOGO: 5,
      LOGO_TOP: 620,
      LOGO_HEIGHT: 60,
      LOGO_LEFT_DELTA: 120,
      LOGO_RIGHT_DELTA: 330,
    },
    {
      IMAGE_NAME_PREFIX: '7-representates-acumulacion-titular',
      MAIN_TOP: 680,
      MAIN_HEIGHT: 60,
      hasLogos: false,
    },
    {
      IMAGE_NAME_PREFIX: '8-representates-acumulacion-1',
      MAIN_TOP: 745,
      MAIN_HEIGHT: 60,
      hasLogos: true,
      N_LOGO: 5,
      LOGO_TOP: 745,
      LOGO_HEIGHT: 60,
      LOGO_LEFT_DELTA: 120,
      LOGO_RIGHT_DELTA: 330,
    },
    {
      IMAGE_NAME_PREFIX: '9-representates-acumulacion-2',
      MAIN_TOP: 810,
      MAIN_HEIGHT: 60,
      hasLogos: true,
      N_LOGO: 4,
      LOGO_TOP: 810,
      LOGO_HEIGHT: 60,
      LOGO_LEFT_DELTA: 120,
      LOGO_RIGHT_DELTA: 330,
    },
    {
      IMAGE_NAME_PREFIX: '10-representates-acumulacion-3',
      MAIN_TOP: 870,
      MAIN_HEIGHT: 60,
      hasLogos: true,
      N_LOGO: 2,
      LOGO_TOP: 870,
      LOGO_HEIGHT: 60,
      LOGO_LEFT_DELTA: 120,
      LOGO_RIGHT_DELTA: 330,
    },
    {
      IMAGE_NAME_PREFIX: '11-representates-acumulacion-4',
      MAIN_TOP: 935,
      MAIN_HEIGHT: 60,
      hasLogos: true,
      N_LOGO: 2,
      LOGO_TOP: 935,
      LOGO_HEIGHT: 60,
      LOGO_LEFT_DELTA: 120,
      LOGO_RIGHT_DELTA: 330,
    },
    {
      IMAGE_NAME_PREFIX: '12-representates-acumulacion-5',
      MAIN_TOP: 1000,
      MAIN_HEIGHT: 60,
      hasLogos: true,
      N_LOGO: 2,
      LOGO_TOP: 1000,
      LOGO_HEIGHT: 60,
      LOGO_LEFT_DELTA: 120,
      LOGO_RIGHT_DELTA: 330,
    },
    {
      IMAGE_NAME_PREFIX: '13-representates-acumulacion-6',
      MAIN_TOP: 1060,
      MAIN_HEIGHT: 60,
      hasLogos: true,
      N_LOGO: 2,
      LOGO_TOP: 1060,
      LOGO_HEIGHT: 60,
      LOGO_LEFT_DELTA: 120,
      LOGO_RIGHT_DELTA: 330,
    },
    {
      IMAGE_NAME_PREFIX: '14-senadores-acumulacion-titular',
      MAIN_TOP: 1120,
      MAIN_HEIGHT: 60,
      hasLogos: false,
    },
    {
      IMAGE_NAME_PREFIX: '15-senadores-acumulacion-1',
      MAIN_TOP: 1185,
      MAIN_HEIGHT: 60,
      hasLogos: true,
      N_LOGO: 6,
      LOGO_TOP: 1185,
      LOGO_HEIGHT: 60,
      LOGO_LEFT_DELTA: 120,
      LOGO_RIGHT_DELTA: 330,
    },
    {
      IMAGE_NAME_PREFIX: '16-senadores-acumulacion-2',
      MAIN_TOP: 1245,
      MAIN_HEIGHT: 60,
      hasLogos: true,
      N_LOGO: 4,
      LOGO_TOP: 1245,
      LOGO_HEIGHT: 60,
      LOGO_LEFT_DELTA: 120,
      LOGO_RIGHT_DELTA: 330,
    },
    {
      IMAGE_NAME_PREFIX: '17-senadores-acumulacion-3',
      MAIN_TOP: 1310,
      MAIN_HEIGHT: 60,
      hasLogos: true,
      N_LOGO: 2,
      LOGO_TOP: 1310,
      LOGO_HEIGHT: 60,
      LOGO_LEFT_DELTA: 120,
      LOGO_RIGHT_DELTA: 330,
    },
    {
      IMAGE_NAME_PREFIX: '18-senadores-acumulacion-4',
      MAIN_TOP: 1375,
      MAIN_HEIGHT: 60,
      hasLogos: true,
      N_LOGO: 2,
      LOGO_TOP: 1375,
      LOGO_HEIGHT: 60,
      LOGO_LEFT_DELTA: 120,
      LOGO_RIGHT_DELTA: 330,
    },
    {
      IMAGE_NAME_PREFIX: '19-senadores-acumulacion-5',
      MAIN_TOP: 1435,
      MAIN_HEIGHT: 60,
      hasLogos: true,
      N_LOGO: 2,
      LOGO_TOP: 1435,
      LOGO_HEIGHT: 60,
      LOGO_LEFT_DELTA: 120,
      LOGO_RIGHT_DELTA: 330,
    },
    {
      IMAGE_NAME_PREFIX: '20-senadores-acumulacion-6',
      MAIN_TOP: 1500,
      MAIN_HEIGHT: 60,
      hasLogos: true,
      N_LOGO: 2,
      LOGO_TOP: 1500,
      LOGO_HEIGHT: 60,
      LOGO_LEFT_DELTA: 120,
      LOGO_RIGHT_DELTA: 330,
    },
  ],
};
