export interface BaseRow {
  IMAGE_NAME_PREFIX?: string;
  MAIN_TOP?: number;
  MAIN_HEIGHT?: number;
  hasLogos?: boolean;
}
export interface Row extends BaseRow {
  N_LOGO?: number;
  LOGO_TOP?: number;
  LOGO_HEIGHT?: number;
  LOGO_LEFT_DELTA?: number;
  LOGO_RIGHT_DELTA?: number;
}
interface DefaultValues {
  [index: string]: BaseRow | Row;
}
const defaultRowValues: DefaultValues = {
  '1': {
    IMAGE_NAME_PREFIX: '1-partido',
    MAIN_TOP: 110,
    MAIN_HEIGHT: 255,
    hasLogos: true,
    N_LOGO: 5,
    LOGO_TOP: 115,
    LOGO_HEIGHT: 110,
    LOGO_LEFT_DELTA: 130,
    LOGO_RIGHT_DELTA: 265,
  },
  '2': {
    IMAGE_NAME_PREFIX: '2-representates-distrito-titular',
    MAIN_TOP: 370,
    MAIN_HEIGHT: 60,
    hasLogos: false,
  },
  '3': {
    IMAGE_NAME_PREFIX: '3-representates-distrito',
    MAIN_TOP: 430,
    MAIN_HEIGHT: 60,
    hasLogos: true,
    N_LOGO: 5,
    LOGO_TOP: 430,
    LOGO_HEIGHT: 60,
    LOGO_LEFT_DELTA: 120,
    LOGO_RIGHT_DELTA: 330,
  },
  '4': {
    IMAGE_NAME_PREFIX: '4-senadores-titular',
    MAIN_TOP: 495,
    MAIN_HEIGHT: 60,
    hasLogos: false,
  },
  '5': {
    IMAGE_NAME_PREFIX: '5-senadores-1',
    MAIN_TOP: 555,
    MAIN_HEIGHT: 60,
    hasLogos: true,
    N_LOGO: 5,
    LOGO_TOP: 555,
    LOGO_HEIGHT: 60,
    LOGO_LEFT_DELTA: 120,
    LOGO_RIGHT_DELTA: 330,
  },
  '6': {
    IMAGE_NAME_PREFIX: '6-senadores-2',
    MAIN_TOP: 620,
    MAIN_HEIGHT: 60,
    hasLogos: true,
    N_LOGO: 4,
    LOGO_TOP: 620,
    LOGO_HEIGHT: 60,
    LOGO_LEFT_DELTA: 120,
    LOGO_RIGHT_DELTA: 330,
  },
  '7': {
    IMAGE_NAME_PREFIX: '7-representates-acumulacion-titular',
    MAIN_TOP: 680,
    MAIN_HEIGHT: 60,
    hasLogos: false,
  },
  '8': {
    IMAGE_NAME_PREFIX: '8-representates-acumulacion-1',
    MAIN_TOP: 745,
    MAIN_HEIGHT: 60,
    hasLogos: true,
    N_LOGO: 5,
    LOGO_TOP: 745,
    LOGO_HEIGHT: 60,
    LOGO_LEFT_DELTA: 120,
    LOGO_RIGHT_DELTA: 330,
  },
  '9': {
    IMAGE_NAME_PREFIX: '9-representates-acumulacion-2',
    MAIN_TOP: 810,
    MAIN_HEIGHT: 60,
    hasLogos: true,
    N_LOGO: 4,
    LOGO_TOP: 810,
    LOGO_HEIGHT: 60,
    LOGO_LEFT_DELTA: 120,
    LOGO_RIGHT_DELTA: 330,
  },
  '10': {
    IMAGE_NAME_PREFIX: '10-representates-acumulacion-3',
    MAIN_TOP: 870,
    MAIN_HEIGHT: 60,
    hasLogos: true,
    N_LOGO: 2,
    LOGO_TOP: 870,
    LOGO_HEIGHT: 60,
    LOGO_LEFT_DELTA: 120,
    LOGO_RIGHT_DELTA: 330,
  },
  '11': {
    IMAGE_NAME_PREFIX: '11-representates-acumulacion-4',
    MAIN_TOP: 935,
    MAIN_HEIGHT: 60,
    hasLogos: true,
    N_LOGO: 2,
    LOGO_TOP: 935,
    LOGO_HEIGHT: 60,
    LOGO_LEFT_DELTA: 120,
    LOGO_RIGHT_DELTA: 330,
  },
  '12': {
    IMAGE_NAME_PREFIX: '12-representates-acumulacion-5',
    MAIN_TOP: 1000,
    MAIN_HEIGHT: 60,
    hasLogos: true,
    N_LOGO: 2,
    LOGO_TOP: 1000,
    LOGO_HEIGHT: 60,
    LOGO_LEFT_DELTA: 120,
    LOGO_RIGHT_DELTA: 330,
  },
  '13': {
    IMAGE_NAME_PREFIX: '13-representates-acumulacion-6',
    MAIN_TOP: 1060,
    MAIN_HEIGHT: 60,
    hasLogos: true,
    N_LOGO: 2,
    LOGO_TOP: 1060,
    LOGO_HEIGHT: 60,
    LOGO_LEFT_DELTA: 120,
    LOGO_RIGHT_DELTA: 330,
  },
  '14': {
    IMAGE_NAME_PREFIX: '14-senadores-acumulacion-titular',
    MAIN_TOP: 1120,
    MAIN_HEIGHT: 60,
    hasLogos: false,
  },
  '15': {
    IMAGE_NAME_PREFIX: '15-senadores-acumulacion-1',
    MAIN_TOP: 1185,
    MAIN_HEIGHT: 60,
    hasLogos: true,
    N_LOGO: 6,
    LOGO_TOP: 1185,
    LOGO_HEIGHT: 60,
    LOGO_LEFT_DELTA: 120,
    LOGO_RIGHT_DELTA: 330,
  },
  '16': {
    IMAGE_NAME_PREFIX: '16-senadores-acumulacion-2',
    MAIN_TOP: 1245,
    MAIN_HEIGHT: 60,
    hasLogos: true,
    N_LOGO: 4,
    LOGO_TOP: 1245,
    LOGO_HEIGHT: 60,
    LOGO_LEFT_DELTA: 120,
    LOGO_RIGHT_DELTA: 330,
  },
  '17': {
    IMAGE_NAME_PREFIX: '17-senadores-acumulacion-3',
    MAIN_TOP: 1310,
    MAIN_HEIGHT: 60,
    hasLogos: true,
    N_LOGO: 2,
    LOGO_TOP: 1310,
    LOGO_HEIGHT: 60,
    LOGO_LEFT_DELTA: 120,
    LOGO_RIGHT_DELTA: 330,
  },
  '18': {
    IMAGE_NAME_PREFIX: '18-senadores-acumulacion-4',
    MAIN_TOP: 1375,
    MAIN_HEIGHT: 60,
    hasLogos: true,
    N_LOGO: 2,
    LOGO_TOP: 1375,
    LOGO_HEIGHT: 60,
    LOGO_LEFT_DELTA: 120,
    LOGO_RIGHT_DELTA: 330,
  },
  '19': {
    IMAGE_NAME_PREFIX: '19-senadores-acumulacion-5',
    MAIN_TOP: 1435,
    MAIN_HEIGHT: 60,
    hasLogos: true,
    N_LOGO: 2,
    LOGO_TOP: 1435,
    LOGO_HEIGHT: 60,
    LOGO_LEFT_DELTA: 120,
    LOGO_RIGHT_DELTA: 330,
  },
  '20': {
    IMAGE_NAME_PREFIX: '20-senadores-acumulacion-6',
    MAIN_TOP: 1500,
    MAIN_HEIGHT: 60,
    hasLogos: true,
    N_LOGO: 2,
    LOGO_TOP: 1500,
    LOGO_HEIGHT: 60,
    LOGO_LEFT_DELTA: 120,
    LOGO_RIGHT_DELTA: 330,
  },
};

export function getRowConfig(rowNumber: number, options?: BaseRow | Row) {
  const defaultConfig: BaseRow | Row = defaultRowValues[`${rowNumber}`];
  return { ...defaultConfig, ...options };
}
