export const config = {
  filePath: '../static/2020/_ESTATAL_17-1.jpg',
  N_COLUMNS: 6,
  CELL_WIDTH: 385,
  STARTING_X: 195,
  PERCENTAGE_DELTA: 0.01,
  rows: [
    {
      IMAGE_NAME_PREFIX: 'partido',
      MAIN_TOP: 115,
      MAIN_HEIGHT: 245,
      hasLogos: true,
      N_LOGO: 5,
      LOGO_TOP: 125,
      LOGO_HEIGHT: 100,
      LOGO_LEFT_DELTA: 130,
      LOGO_RIGHT_DELTA: 265,
    },
    {
      IMAGE_NAME_PREFIX: 'gobernador-titular',
      MAIN_TOP: 370,
      MAIN_HEIGHT: 60,
      hasLogos: false,
    },
    {
      IMAGE_NAME_PREFIX: 'gobernador',
      MAIN_TOP: 430,
      MAIN_HEIGHT: 60,
      hasLogos: true,
      N_LOGO: 6,
      LOGO_TOP: 430,
      LOGO_HEIGHT: 60,
      LOGO_LEFT_DELTA: 120,
      LOGO_RIGHT_DELTA: 330,
    },
    {
      IMAGE_NAME_PREFIX: 'comisionado-titular',
      MAIN_TOP: 495,
      MAIN_HEIGHT: 60,
      hasLogos: false,
    },
    {
      IMAGE_NAME_PREFIX: 'comisionado',
      MAIN_TOP: 555,
      MAIN_HEIGHT: 60,
      hasLogos: true,
      N_LOGO: 6,
      LOGO_TOP: 555,
      LOGO_HEIGHT: 60,
      LOGO_LEFT_DELTA: 120,
      LOGO_RIGHT_DELTA: 330,
    },
  ],
};
