export const config = {
  filePath: '../static/gov.jpg',
  N_COLUMNS: 7,
  CELL_WIDTH: 385,
  STARTING_X: 195,
  PERCENTAGE_DELTA: 0.01,
  rows: [{
    IMAGE_NAME_PREFIX: 'partido',
    MAIN_TOP: 365,
    MAIN_HEIGHT: 255,
    hasLogos: true,
    N_LOGO: 4,
    LOGO_TOP: 370,
    LOGO_HEIGHT: 110,
    LOGO_LEFT_DELTA: 130,
    LOGO_RIGHT_DELTA: 265
  }, {
    IMAGE_NAME_PREFIX: 'gobernador-titular',
    MAIN_TOP: 620,
    MAIN_HEIGHT: 60,
    hasLogos: false,
  }, {
    IMAGE_NAME_PREFIX: 'gobernador',
    MAIN_TOP: 680,
    MAIN_HEIGHT: 60,
    hasLogos: true,
    N_LOGO: 6,
    LOGO_TOP: 680,
    LOGO_HEIGHT: 60,
    LOGO_LEFT_DELTA: 120,
    LOGO_RIGHT_DELTA: 330
  }, {
    IMAGE_NAME_PREFIX: 'comisionado-titular',
    MAIN_TOP: 740,
    MAIN_HEIGHT: 60,
    hasLogos: false,
  }, {
    IMAGE_NAME_PREFIX: 'comisionado',
    MAIN_TOP: 810,
    MAIN_HEIGHT: 60,
    hasLogos: true,
    N_LOGO: 6,
    LOGO_TOP: 810,
    LOGO_HEIGHT: 60,
    LOGO_LEFT_DELTA: 120,
    LOGO_RIGHT_DELTA: 330
  }]
};
