export const config = {
  filePath: '../static/Patillas-1.jpg',
  N_COLUMNS: 3,
  CELL_WIDTH: 385,
  STARTING_X: 195,
  PERCENTAGE_DELTA: 0.01,
  rows: [
    {
      IMAGE_NAME_PREFIX: '1-partido',
      MAIN_TOP: 110,
      MAIN_HEIGHT: 255,
      hasLogos: true,
      N_LOGO: 3,
      LOGO_TOP: 115,
      LOGO_HEIGHT: 110,
      LOGO_LEFT_DELTA: 130,
      LOGO_RIGHT_DELTA: 265,
    },
    {
      IMAGE_NAME_PREFIX: '2-alcalde-titular',
      MAIN_TOP: 370,
      MAIN_HEIGHT: 60,
      hasLogos: false,
    },
    {
      IMAGE_NAME_PREFIX: '3-alcalde',
      MAIN_TOP: 430,
      MAIN_HEIGHT: 60,
      hasLogos: true,
      N_LOGO: 3,
      LOGO_TOP: 430,
      LOGO_HEIGHT: 60,
      LOGO_LEFT_DELTA: 120,
      LOGO_RIGHT_DELTA: 330,
    },
    {
      IMAGE_NAME_PREFIX: '4-legisladores-titular',
      MAIN_TOP: 495,
      MAIN_HEIGHT: 60,
      hasLogos: false,
    },
    {
      IMAGE_NAME_PREFIX: '5-legisladores-1',
      MAIN_TOP: 555,
      MAIN_HEIGHT: 60,
      hasLogos: false,
    },
    {
      IMAGE_NAME_PREFIX: '5-legisladores-2',
      MAIN_TOP: 615,
      MAIN_HEIGHT: 60,
      hasLogos: false,
    },
    {
      IMAGE_NAME_PREFIX: '5-legisladores-3',
      MAIN_TOP: 675,
      MAIN_HEIGHT: 60,
      hasLogos: false,
    },
    {
      IMAGE_NAME_PREFIX: '5-legisladores-4',
      MAIN_TOP: 735,
      MAIN_HEIGHT: 60,
      hasLogos: false,
    },
    {
      IMAGE_NAME_PREFIX: '5-legisladores-5',
      MAIN_TOP: 795,
      MAIN_HEIGHT: 60,
      hasLogos: false,
    },
    {
      IMAGE_NAME_PREFIX: '5-legisladores-6',
      MAIN_TOP: 855,
      MAIN_HEIGHT: 60,
      hasLogos: false,
    },
    {
      IMAGE_NAME_PREFIX: '5-legisladores-7',
      MAIN_TOP: 915,
      MAIN_HEIGHT: 60,
      hasLogos: false,
    },
    {
      IMAGE_NAME_PREFIX: '5-legisladores-8',
      MAIN_TOP: 975,
      MAIN_HEIGHT: 60,
      hasLogos: false,
    },
    {
      IMAGE_NAME_PREFIX: '5-legisladores-9',
      MAIN_TOP: 1035,
      MAIN_HEIGHT: 60,
      hasLogos: false,
    },
  ],
};
