export const config = {
  filePath: '../static/municipal/097_Culebra_MUNICIPAL_11-1.jpg',
  N_COLUMNS: 4,
  CELL_WIDTH: 385,
  STARTING_X: 195,
  PERCENTAGE_DELTA: 0.01,
  rows: [
    {
      IMAGE_NAME_PREFIX: '1-partido',
      MAIN_TOP: 110,
      MAIN_HEIGHT: 255,
      hasLogos: true,
      N_LOGO: 3,
      LOGO_TOP: 115,
      LOGO_HEIGHT: 110,
      LOGO_LEFT_DELTA: 130,
      LOGO_RIGHT_DELTA: 265,
    },
    {
      IMAGE_NAME_PREFIX: '2-alcalde-titular',
      MAIN_TOP: 370,
      MAIN_HEIGHT: 60,
      hasLogos: false,
    },
    {
      IMAGE_NAME_PREFIX: '3-alcalde',
      MAIN_TOP: 430,
      MAIN_HEIGHT: 60,
      hasLogos: true,
      N_LOGO: 3,
      LOGO_TOP: 430,
      LOGO_HEIGHT: 60,
      LOGO_LEFT_DELTA: 120,
      LOGO_RIGHT_DELTA: 330,
    },
    {
      IMAGE_NAME_PREFIX: '4-legisladores-titular',
      MAIN_TOP: 495,
      MAIN_HEIGHT: 60,
      hasLogos: false,
    },
    {
      IMAGE_NAME_PREFIX: '5-legisladores-1',
      MAIN_TOP: 560,
      MAIN_HEIGHT: 60,
      hasLogos: false,
    },
    {
      IMAGE_NAME_PREFIX: '5-legisladores-2',
      MAIN_TOP: 620,
      MAIN_HEIGHT: 60,
      hasLogos: false,
    },
    {
      IMAGE_NAME_PREFIX: '5-legisladores-3',
      MAIN_TOP: 680,
      MAIN_HEIGHT: 60,
      hasLogos: false,
    },
    {
      IMAGE_NAME_PREFIX: '5-legisladores-4',
      MAIN_TOP: 745,
      MAIN_HEIGHT: 60,
      hasLogos: false,
    },
  ],
};
